# Generated by Django 5.2.9 on 2026-03-11 08:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField()),
                ("queued", models.BooleanField(default=False)),
                ("subject", models.TextField()),
                ("body_text", models.TextField()),
                ("body_html", models.TextField()),
                ("send_attempt_count", models.IntegerField(default=0)),
                ("external_id", models.UUIDField(default=uuid.uuid4)),
                ("audit_action", models.CharField(default="", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="SuomifiPersistence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("continuation_token", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField()),
                ("suomifi_id", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(null=True)),
                ("read_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent_suomifi", "Sent via Suomi.fi messages"),
                            ("sent_email", "Sent via e-mail"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                    ),
                ),
                (
                    "queued_message",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_report",
                        to="message_service.message",
                    ),
                ),
            ],
        ),
    ]
