# Generated by Django 5.2.9 on 2026-03-11 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryreport",
            name="message_type",
            field=models.TextField(
                choices=[
                    ("other", "Other"),
                    ("due_date_extended", "Due date extended"),
                    ("status_sent", "Status: sent"),
                    ("status_received", "Status: received"),
                    ("status_handling", "Status: handling"),
                    ("status_resolved_via_e_service", "Status: resolved via e-service"),
                    ("status_resolved_via_mail", "Status: resolved via mail"),
                ],
                default="other",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.TextField(
                choices=[
                    ("other", "Other"),
                    ("due_date_extended", "Due date extended"),
                    ("status_sent", "Status: sent"),
                    ("status_received", "Status: received"),
                    ("status_handling", "Status: handling"),
                    ("status_resolved_via_e_service", "Status: resolved via e-service"),
                    ("status_resolved_via_mail", "Status: resolved via mail"),
                ],
                default="other",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryreport",
            name="status",
            field=models.TextField(
                choices=[
                    ("queued", "Queued"),
                    ("sent_suomifi", "Sent via Suomi.fi messages"),
                    ("sent_email", "Sent via e-mail"),
                    ("read_suomifi", "Read via Suomi.fi messages"),
                    ("failed", "Failed"),
                ],
                default="queued",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "message_type__in",
                        [
                            "other",
                            "due_date_extended",
                            "status_sent",
                            "status_received",
                            "status_handling",
                            "status_resolved_via_e_service",
                            "status_resolved_via_mail",
                        ],
                    )
                ),
                name="check_valid_message_type",
            ),
        ),
    ]
