# Generated by Django 5.2.9 on 2026-03-13 12:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "message_service",
            "0002_deliveryreport_message_type_message_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="external_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
