# Generated by Django 5.2.9 on 2026-03-16 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message_service", "0003_alter_message_external_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="send_attempt_count",
            new_name="send_failure_count",
        ),
    ]
