# Generated by Django 5.2.9 on 2026-02-11 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
