# Generated by Django 3.2.16 on 2023-05-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_audit_event_auditlog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
