# Generated by Django 3.2.16 on 2023-03-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_message_auditlog_audit_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='sent_at',
        ),
    ]
