# Generated by Django 3.2.16 on 2023-05-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_auditlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='message',
            field=models.JSONField(default=dict),
        ),
    ]
