# Generated by Django 5.2.6 on 2025-09-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pysakoinnin_sahk_asiointi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_api_use",
            field=models.DateField(
                blank=True, null=True, verbose_name="Latest API token usage date"
            ),
        ),
    ]
